# Generated by Django 4.0.4 on 2022-04-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dictionnaire_t',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField()),
                ('classification', models.TextField()),
                ('definition', models.TextField()),
                ('url_image', models.URLField(default=None, max_length=50)),
                ('frequence', models.IntegerField(default=None)),
            ],
        ),
    ]
