# Generated by Django 4.0.4 on 2022-04-21 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dictionnaire_t',
            new_name='dictionary_t',
        ),
    ]
