# Generated by Django 4.0.4 on 2022-04-22 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_rename_dictionnaire_t_dictionary_t'),
    ]

    operations = [
        migrations.CreateModel(
            name='dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('classification', models.CharField(max_length=10)),
                ('definition', models.CharField(max_length=100)),
                ('url_image', models.URLField(default=None, max_length=50)),
                ('frequence', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField(default=None)),
                ('created_at', models.DateField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictionary.dictionary')),
            ],
        ),
        migrations.DeleteModel(
            name='dictionary_t',
        ),
    ]
