# Generated by Django 4.0.4 on 2022-04-23 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_rename_dictionary_dictionary_t_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictionary_t',
            old_name='frequence',
            new_name='frequency',
        ),
    ]
