# Generated by Django 4.0.4 on 2022-04-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_rename_frequence_dictionary_t_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary_t',
            name='frequency',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='dictionary_t',
            name='url_image',
            field=models.URLField(blank=True, default='', max_length=50),
        ),
    ]
