# Generated by Django 4.0.4 on 2022-04-23 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_alter_dictionary_t_frequency_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dictionary_t',
            new_name='Dictionary2_t',
        ),
        migrations.RenameModel(
            old_name='history_t',
            new_name='History2_t',
        ),
    ]
