# Generated by Django 4.0.4 on 2022-04-23 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_rename_dictionary_t_dictionary2_t_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dictionary2_t',
            new_name='Dictionary_t',
        ),
        migrations.RenameModel(
            old_name='History2_t',
            new_name='History_t',
        ),
    ]
