# Generated by Django 4.0.4 on 2022-04-26 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0008_rename_dictionary2_t_dictionary_t_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_t',
            name='user_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
